# Generated by Django 4.2.5 on 2023-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AddField(
            model_name='ejemplo',
            name='autor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
