# Generated by Django 4.2.5 on 2023-10-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_blog_fondo_alter_blog_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='fondo',
        ),
    ]
