# Generated by Django 4.2.5 on 2023-10-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
