# Generated by Django 4.2.5 on 2023-10-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movil',
            name='imagen',
            field=models.ImageField(null=True, upload_to='galeria'),
        ),
    ]
